blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/kiki7000/discord.py-buttons/discussions/categories/q-a
    about: Please ask questions at the discussions