name: Black Formatter

on:
  push:
    branches:
    - master

jobs:
  apply-black:
    if: contains(github.event.commits.*.message,'GitHub Actions - Formatted using black formatter.') == false
    name: Apply Black Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0 
    - name: Run Black
      uses: lgeiger/black-action@master
      with:
        args: .
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSWORD }}
        git-user-signingkey: true
        git-commit-gpgsign: true
    - name: Git config
      run: |
        git config --local remote.origin.url "https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git"
    - name: Commit files
      run: git commit -S -am 'GitHub Actions - Formatted using black formatter.'
    - name: Push changes
      run: git push origin main 